### ISSUE TITLE
Cannot PATCH health

### ISSUE THREAD

**Issue by webdevbrian** [jeff-1amstudios/restful-doom#10]
Just testing through things, it doesn't seem that PATCHing the health works (through `api/player`, but it works with armor.

**Comment by jeff-1amstudios** [comment]
thanks for the report, I did indeed miss the health field. I'm sure you'll be excited to learn this is now fixed in https://github.com/jeff-1amstudios/restful-doom/commit/e221b269d05c4f870922808dce7f3bf273235f45 :P
