### ISSUE TITLE
Unable to build on OSX

### ISSUE THREAD

**Issue by Brodan** [jeff-1amstudios/restful-doom#3]
I'm currently on OSX 10.12.5 specifically. I followed these steps:
1. `git clone https://github.com/jeff-1amstudios/restful-doom.git`
2. `./configure-and-build.sh`
```
=======================================================
Building restful-doom...
=======================================================
 
autotools not installed; please run:
    chocpkg install native:autotools
```
3. `cd chocpkg/chocpkg/`
4. `./chocpkg install native:autotools`
5. `./chocpkg install chocolate-doom`
```
  Unknown variant stable for package chocolate-doom.
```

Any suggestions? Did I miss a step?

**Comment by KingOfPoptart** [comment]
I'm having the same issue

**Comment by seusher** [comment]
I had to use this script to get the correct tooling on macOS Sierra 10.12.6

https://gist.github.com/perfaram/1dad8da22b324bc4016c

Everything built fine after running that.

**Comment by KingOfPoptart** [comment]
@seusher that did the trick for me! 

Steps that I specifically had to do:

```
#Started from clean slate (not doing so failed)
rm -rf restful-doom

#cltools.sh taken from https://gist.github.com/perfaram/1dad8da22b324bc4016c
./cltools.sh

git clone https://github.com/jeff-1amstudios/restful-doom
cd restful-doom
./configure-and-build.sh
make

#Run doom!
src/restful-doom -iwad [path to doom.wad] -apiport 6666
```

**Comment by jeff-1amstudios** [comment]
Ah thanks for that. I think I had previously installed them via brew

**Comment by jeff-1amstudios** [comment]
Will take a look
