### ISSUE TITLE
Activate end of map switch

### ISSUE THREAD

**Issue by ghost** [jeff-1amstudios/restful-doom#4]
Thanks, this has been great fun.

I've done enough of the first map to get to the last switch to end the map and go to the next one.

Checking objects and doors close to me do not give me an ID to patch against.

Any ideas how I activate the end of map switch?

[Switch](http://imgur.com/a/BnuGE)

**Comment by KingOfPoptart** [comment]
It doesn't look like the "Use(open)" key is currently implemented - there's no way I can tell to send a Space bar via the REST API currently

An update to https://github.com/jeff-1amstudios/restful-doom/blob/master/src/doom/api_player_controller.c  would be necessary I think

**Comment by KingOfPoptart** [comment]
I've written a pull request to add this ability 

https://github.com/jeff-1amstudios/restful-doom/pull/7

**Comment by ghost** [comment]
Amazing - I'll test it out after breakfast. Use(open) as a callable object should resolve other items too (switches/screen progression etc).

Having a stab at Twitch integration here - https://www.twitch.tv/dddanmar

**Comment by KingOfPoptart** [comment]
Ha!  I'm building the same thing :D 

https://github.com/KingOfPoptart/doomTwitchShooter

**Comment by ghost** [comment]
Great! Happy to share what I've got so far (Python/Twitch IRC/Requests)
https://github.com/dddanmar/twitch-plays-doom

**Comment by ghost** [comment]
Tested @KingOfPoptart 's changes, works perfectly.

Solves other game play issues as well.

**Comment by jeff-1amstudios** [comment]
Ah good point! I did start looking at implementing switches as a resource like doors but didn't actually do it. Could be fun exercise for someone to add :)

**Comment by jeff-1amstudios** [comment]
This https://github.com/jeff-1amstudios/restful-doom/commit/f0494af6153a17ae17859b2b3e1e389c1aaee3b9 fixes the immediate issue (inspired by @KingOfPoptart's PR) without adding the switches endpoint.
